# Change these first
owner: hatry4 # Your GitHub organization or username, where this repository lives
repo: hatry4.github.io.status # The name of this repository

sites:
  - name: Hatry4
    url: https://www.hatry4.xyz
  - name: Hatry4 - Docs
    url: https://www.docs.hatry4.xyz
  - name: Kryptonite
    url: https://kryptonite.tk

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: www.status.hatry4.xyz
  # baseUrl: /your-repo-name
  favicon: https://official-hatry4xyz.devhatry4.repl.co/assets/images/logo/hatry4.png
  baseUrl: /hatry4.github.io.status
  theme: dark
  logoUrl: https://official-hatry4xyz.devhatry4.repl.co/assets/images/logo/hatry4.png
  name: 
  introTitle: " "
  introMessage: 
  navbar:
    - title: Hatry4
      href: www.hatry4.xyz
    - title: Status
      href: https://www.status.hatry4.xyz
    - title: Kryptonite
      href: https://Kryptonite.tk
    - title: GitHub
      href: https://github.com/$OWNER/
      
